const Map<String, String> airportMap = {
  'CGK': 'Jakarta - Soekarno-Hatta',
  'HLP': 'Jakarta - Halim Perdanakusuma',
  'DPS': 'Bali - Ngurah Rai',
  'SUB': 'Surabaya - Juanda',
  'UPG': 'Makassar - Sultan Hasanuddin',
  'KNO': 'Medan - Kualanamu',
  'BDO': 'Bandung - Husein Sastranegara',
  'JOG': 'Yogyakarta - Adisutjipto',
  'YIA': 'Yogyakarta - Yogyakarta Intl',
  'SRG': 'Semarang - Ahmad Yani',
  'BPN': 'Balikpapan - Sultan Aji Muhammad Sulaiman',
  'PKU': 'Pekanbaru - Sultan Syarif Kasim II',
  'PLM': 'Palembang - Sultan Mahmud Badaruddin II',
  'BTH': 'Batam - Hang Nadim',
  'LOP': 'Lombok - Lombok Intl',
  'PNK': 'Pontianak - Supadio',
  'MDC': 'Manado - Sam Ratulangi',
  'BKS': 'Bengkulu - Fatmawati Soekarno',
  'MLG': 'Malang - Abdul Rachman Saleh',
  'PDG': 'Padang - Minangkabau',
  'TJQ': 'Tanjung Pandan - H.A.S. Hanandjoeddin',
  'TRK': 'Tarakan - Juwata',
  'TIM': 'Timika - Mozes Kilangin',
  'DJJ': 'Jayapura - Sentani',
  'BTJ': 'Banda Aceh - Sultan Iskandar Muda',
  'SMQ': 'Samarinda - Temindung',
  'KDI': 'Kendari - Haluoleo',
  'LBJ': 'Labuan Bajo - Komodo',
  'RKO': 'Raja Ampat - Marinda',
  'SOQ': 'Sumbawa - Sultan Muhammad Salahuddin',
  'NDA': 'Nias - Binaka',
};
